name: Test

on:
  push:
    branches:
      - main
  milestone:
    types: [closed]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Create a release draft for a milestone
        id: create-release-draft
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print the URL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}